/****************************************************************************
  * apps/tencent/wifi_sdk/adapt/src/ecr_qcloud_led.c
 *
 *   Copyright (C) 2021 ESWIN. All rights reserved.
 *   Author:  FeixiongZhang<zhangfeixiong@eswin.com>
 *   Revision history:
 *   2021.08.25 - Initial version.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <limits.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include "qcloud_iot_export.h"
#include "qcloud_iot_import.h"
#include "utils_timer.h"
#include "freertos/FreeRTOS.h"
#include "easyflash.h"
#include "data_template_client.h"
#include "ecr_qcloud_led_driver.h"
#include "ecr_qcloud_led.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

#define MQTT_TIMEOUT_VALUE_MS     (10 * 1000)
#define TOTAL_PROPERTY_COUNT      4
#define MAX_STR_NAME_LEN          (64)

#ifdef EVENT_POST_ENABLED
#define EVENT_COUNTS              (3)
#define MAX_EVENT_STR_MESSAGE_LEN (64)
#define MAX_EVENT_STR_NAME_LEN    (64)
#endif

/****************************************************************************
 * Private Data
 ****************************************************************************/

DeviceInfo sg_devInfo;
static Timer      sg_MonitorClient;

static MQTTEventType sg_subscribe_event_result = MQTT_EVENT_UNDEF;
static bool          sg_control_msg_arrived    = false;
static char          sg_data_report_buffer[2048];
static size_t        sg_data_report_buffersize = sizeof(sg_data_report_buffer) / sizeof(sg_data_report_buffer[0]);

static sDataPoint sg_DataTemplate[TOTAL_PROPERTY_COUNT];

static ProductDataDefine sg_ProductData;

/* 数据模板格式定义*/
static void _init_data_template(void)
{
    memset((void *)&sg_ProductData, 0, sizeof(ProductDataDefine));

    sg_ProductData.m_light_switch         = 0;
    sg_DataTemplate[0].data_property.key  = "power_switch";
    sg_DataTemplate[0].data_property.data = &sg_ProductData.m_light_switch;
    sg_DataTemplate[0].data_property.type = TYPE_TEMPLATE_BOOL;

    sg_ProductData.m_color                = eCOLOR_RED;
    sg_DataTemplate[1].data_property.key  = "color";
    sg_DataTemplate[1].data_property.data = &sg_ProductData.m_color;
    sg_DataTemplate[1].data_property.type = TYPE_TEMPLATE_ENUM;

    sg_ProductData.m_brightness           = 0;
    sg_DataTemplate[2].data_property.key  = "brightness";
    sg_DataTemplate[2].data_property.data = &sg_ProductData.m_brightness;
    sg_DataTemplate[2].data_property.type = TYPE_TEMPLATE_INT;

    strncpy(sg_ProductData.m_name, sg_devInfo.device_name, MAX_STR_NAME_LEN);
    sg_ProductData.m_name[strlen(sg_devInfo.device_name)] = '\0';
    sg_DataTemplate[3].data_property.key                  = "name";
    sg_DataTemplate[3].data_property.data                 = sg_ProductData.m_name;
    sg_DataTemplate[3].data_property.data_buff_len        = MAX_STR_NAME_LEN;
    sg_DataTemplate[3].data_property.type                 = TYPE_TEMPLATE_STRING;
};


/*event_config.c can be generated by tools/codegen.py -c xx/product.json*/
/*-----------------event config start  -------------------*/

#ifdef EVENT_POST_ENABLED

static TYPE_DEF_TEMPLATE_BOOL   sg_status;
static TYPE_DEF_TEMPLATE_STRING sg_message[MAX_EVENT_STR_MESSAGE_LEN + 1];
static DeviceProperty           g_propertyEvent_status_report[] = {
    {.key = "status", .data = &sg_status, .type = TYPE_TEMPLATE_BOOL},
    {.key = "message", .data = sg_message, .type = TYPE_TEMPLATE_STRING},
};

static TYPE_DEF_TEMPLATE_FLOAT sg_voltage;
static DeviceProperty          g_propertyEvent_low_voltage[] = {
    {.key = "voltage", .data = &sg_voltage, .type = TYPE_TEMPLATE_FLOAT},
};

static TYPE_DEF_TEMPLATE_STRING sg_name[MAX_EVENT_STR_NAME_LEN + 1];
static TYPE_DEF_TEMPLATE_INT    sg_error_code;
static DeviceProperty           g_propertyEvent_hardware_fault[] = {
    {.key = "name", .data = sg_name, .type = TYPE_TEMPLATE_STRING},
    {.key = "error_code", .data = &sg_error_code, .type = TYPE_TEMPLATE_INT},
};

static sEvent g_events[] = {
    {
        .event_name   = "status_report",
        .type         = "info",
        .timestamp    = 0,
        .eventDataNum = sizeof(g_propertyEvent_status_report) / sizeof(g_propertyEvent_status_report[0]),
        .pEventData   = g_propertyEvent_status_report,
    },
    {
        .event_name   = "low_voltage",
        .type         = "alert",
        .timestamp    = 0,
        .eventDataNum = sizeof(g_propertyEvent_low_voltage) / sizeof(g_propertyEvent_low_voltage[0]),
        .pEventData   = g_propertyEvent_low_voltage,
    },
    {
        .event_name   = "hardware_fault",
        .type         = "fault",
        .timestamp    = 0,
        .eventDataNum = sizeof(g_propertyEvent_hardware_fault) / sizeof(g_propertyEvent_hardware_fault[0]),
        .pEventData   = g_propertyEvent_hardware_fault,
    },
};

/*-----------------event config end -------------------*/

/****************************************************************************
 * Private Function
 ****************************************************************************/

/****************************************************************************
 * Name:  update_events_timestamp
 * Description:
 * @brief       update the UTC time of the event
 * @param[out]   pEvents: array of events
 * @param[in]   count: length of event array
 ****************************************************************************/
static void update_events_timestamp(sEvent *pEvents, int count)
{
    int i;

    for (i = 0; i < count; i++) {
        if (NULL == (&pEvents[i])) {
            Log_e("null event pointer");
            return;
        }
#ifdef EVENT_TIMESTAMP_USED
        pEvents[i].timestamp = HAL_Timer_current_sec();  /* should be UTC and accurate */
#else
        pEvents[i].timestamp = 0;
#endif
    }
}

/****************************************************************************
 * Name:  event_post_cb
 * Description:
 * @brief       callback of event reply
 * @param[in]   pClient: mqtt data template client
 * @param[in]   msg:
 ****************************************************************************/
static void event_post_cb(void *pClient, MQTTMessage *msg)
{
    Log_d("recv event reply, clear event");
    IOT_Event_clearFlag(pClient, FLAG_EVENT0);
}

/****************************************************************************
 * Name:  eventPostCheck
 * Description:
 * @brief       event check and post
 * @param[in]   client: mqtt data template client
 ****************************************************************************/
static void eventPostCheck(void *client)
{
    int      i;
    int      rc;
    uint32_t eflag;
    uint8_t  EventCont;
    sEvent * pEventList[EVENT_COUNTS];

    eflag = IOT_Event_getFlag(client);
    if ((EVENT_COUNTS > 0) && (eflag > 0)) {
        EventCont = 0;
        for (i = 0; i < EVENT_COUNTS; i++) {
            if ((eflag & (1 << i)) & ALL_EVENTS_MASK) {
                pEventList[EventCont++] = &(g_events[i]);
                update_events_timestamp(&g_events[i], 1);
            }
        }

        rc = IOT_Post_Event(client, sg_data_report_buffer, sg_data_report_buffersize, EventCont, pEventList,
                            event_post_cb);  /* 上报数据模板事件 */
        if (rc < 0) {
            Log_e("event post failed: %d", rc);
        } else
            IOT_Event_clearFlag(client, FLAG_EVENT0);
    }
}

#endif /* EVENT_POST_ENABLE */

/*action_config.c can be generated by tools/codegen.py -c xx/product.json*/
/*-----------------action config start  -------------------*/

#ifdef ACTION_ENABLED

#define TOTAL_ACTION_COUNTS (1)

static TYPE_DEF_TEMPLATE_INT sg_blink_in_period    = 5;
static DeviceProperty        g_actionInput_blink[] = {
    {.key = "period", .data = &sg_blink_in_period, .type = TYPE_TEMPLATE_INT}};
static TYPE_DEF_TEMPLATE_BOOL sg_blink_out_result    = 0;
static DeviceProperty         g_actionOutput_blink[] = {

    {.key = "result", .data = &sg_blink_out_result, .type = TYPE_TEMPLATE_BOOL},
};

static DeviceAction g_actions[] = {

    {
        .pActionId  = "blink",
        .timestamp  = 0,
        .input_num  = sizeof(g_actionInput_blink) / sizeof(g_actionInput_blink[0]),
        .output_num = sizeof(g_actionOutput_blink) / sizeof(g_actionOutput_blink[0]),
        .pInput     = g_actionInput_blink,
        .pOutput    = g_actionOutput_blink,
    },
};
/*-----------------action config end    -------------------*/

/****************************************************************************
 * Name:  OnActionCallback
 * Description:
 * @brief       control light blink and replay action resault
 * @param[in]   pClient:
 * @param[in]   pClientToken:
 * @param[in]   pAction: device action
 ****************************************************************************/

static void OnActionCallback(void *pClient, const char *pClientToken, DeviceAction *pAction)
{
    int        i;
    sReplyPara replyPara;

    /* control light blink */
    int             period       = 0;
    DeviceProperty *pActionInput = pAction->pInput;
    for (i = 0; i < pAction->input_num; i++) {
        if (!strcmp(pActionInput[i].key, "period")) {
            period = *((int *)pActionInput[i].data);
        } else {
            Log_e("no such input[%s]!", pActionInput[i].key);
        }
    }

    /* do blink */
    Log_i("do action: light blink");
    for (i = 0; i < 6; i++) {
        // if (i % 2)
        //     set_relay_led_state(LED_ON);
        // else
        //     set_relay_led_state(LED_OFF);
        HAL_SleepMs(period * 1000);
    }

    /* construct output */
    memset((char *)&replyPara, 0, sizeof(sReplyPara));
    replyPara.code       = eDEAL_SUCCESS;
    replyPara.timeout_ms = QCLOUD_IOT_MQTT_COMMAND_TIMEOUT;
    strcpy(replyPara.status_msg, "action execute success!");  // add the message about the action resault

    DeviceProperty *pActionOutnput   = pAction->pOutput;
    *(int *)(pActionOutnput[0].data) = 0;  // set result

    IOT_Action_Reply(pClient, pClientToken, sg_data_report_buffer, sg_data_report_buffersize, pAction, &replyPara);
}

/****************************************************************************
 * Name:  _register_data_template_action
 * Description:
 * @brief       register the device action event of data template client
 * @param[in]   pTemplate_client: data template client
 * @return  0 when success, or err code for failure
 ****************************************************************************/

static int _register_data_template_action(void *pTemplate_client)
{
    int i, rc;

    for (i = 0; i < TOTAL_ACTION_COUNTS; i++) {
        rc = IOT_Template_Register_Action(pTemplate_client, &g_actions[i], OnActionCallback);
        if (rc != QCLOUD_RET_SUCCESS) {
            rc = IOT_Template_Destroy(pTemplate_client);
            Log_e("register device data template action failed, err: %d", rc);
            return rc;
        } else {
            Log_i("data template action=%s registered.", g_actions[i].pActionId);
        }
    }

    return QCLOUD_RET_SUCCESS;
}
#endif /* ACTION_ENABLED */

/****************************************************************************
 * Name:  event_handler
 * Description:
 * @brief       deal with mqtt event
 * @param[in]   pclient: data template client
 * @param[in]   handle_context:
 * @param[in]   msg: event type
 ****************************************************************************/

static void event_handler(void *pclient, void *handle_context, MQTTEventMsg *msg)
{
    uintptr_t packet_id = (uintptr_t)msg->msg;

    switch (msg->event_type) {
        case MQTT_EVENT_UNDEF:
            Log_i("undefined event occur.");
            break;

        case MQTT_EVENT_DISCONNECT:
            Log_i("MQTT disconnect.");
            break;

        case MQTT_EVENT_RECONNECT:
            Log_i("MQTT reconnect.");
            break;

        case MQTT_EVENT_SUBCRIBE_SUCCESS:
            sg_subscribe_event_result = msg->event_type;
            Log_i("subscribe success, packet-id=%u", (unsigned int)packet_id);
            break;

        case MQTT_EVENT_SUBCRIBE_TIMEOUT:
            sg_subscribe_event_result = msg->event_type;
            Log_i("subscribe wait ack timeout, packet-id=%u", (unsigned int)packet_id);
            break;

        case MQTT_EVENT_SUBCRIBE_NACK:
            sg_subscribe_event_result = msg->event_type;
            Log_i("subscribe nack, packet-id=%u", (unsigned int)packet_id);
            break;

        case MQTT_EVENT_PUBLISH_SUCCESS:
            Log_i("publish success, packet-id=%u", (unsigned int)packet_id);
            break;

        case MQTT_EVENT_PUBLISH_TIMEOUT:
            Log_i("publish timeout, packet-id=%u", (unsigned int)packet_id);
            break;

        case MQTT_EVENT_PUBLISH_NACK:
            Log_i("publish nack, packet-id=%u", (unsigned int)packet_id);
            break;
        default:
            Log_i("Should NOT arrive here.");
            break;
    }
}

/****************************************************************************
 * Name:  OnReportReplyCallback
 * Description:
 * @brief       print log information
 * @param[in]   replyAck: number of reply ack
 * @param[in]   pJsonDocument: reply json
 ****************************************************************************/

static void OnReportReplyCallback(void *pClient, Method method, ReplyAck replyAck, const char *pJsonDocument,
                                  void *pUserdata)
{
    Log_i("recv report_reply(ack=%d): %s", replyAck, pJsonDocument);
}

/****************************************************************************
 * Name:  _setup_connect_init_params
 * Description:
 * @brief       setup MQTT construct parameters
 * @param[out]   initParams: save device information
 * @return  0 when success, or err code for failure
 ****************************************************************************/

int _setup_connect_init_params(TemplateInitParams *initParams)
{
    int ret;

    ret = HAL_GetDevInfo((void *)&sg_devInfo);  /* 获取预设 设备信息，产品类型，id，秘钥，地区 */
    if (QCLOUD_RET_SUCCESS != ret) {
        return ret;
    }

    initParams->region        = sg_devInfo.region;
    initParams->product_id    = sg_devInfo.product_id;
    initParams->device_name   = sg_devInfo.device_name;
    initParams->device_secret = sg_devInfo.device_secret;

    initParams->command_timeout        = MQTT_TIMEOUT_VALUE_MS;    /* 超时时间、保活时间、自动连接、 */
    initParams->keep_alive_interval_ms = QCLOUD_IOT_MQTT_KEEP_ALIVE_INTERNAL;
    initParams->auto_connect_enable    = 1;
    initParams->event_handle.h_fp      = event_handler;

    return QCLOUD_RET_SUCCESS;
}

/****************************************************************************
 * Name:  OnControlMsgCallback
 * Description:
 * @brief       control msg from server will trigger this callback
 * @param[in]   pClient: data template client
 * @param[in]   pJsonValueBuffer: receive json
 * @param[in]   valueLength: length of pJsonValueBuffer
 * @param[in]   pProperty: device property handler
 ****************************************************************************/

static void OnControlMsgCallback(void *pClient, const char *pJsonValueBuffer, uint32_t valueLength,
                                 DeviceProperty *pProperty)
{
    int i = 0;

    for (i = 0; i < TOTAL_PROPERTY_COUNT; i++) {
        /* handle self defined string/json here. Other properties are dealed in _handle_delta()*/
        if (strcmp(sg_DataTemplate[i].data_property.key, pProperty->key) == 0) {
            sg_DataTemplate[i].state = eCHANGED;
            Log_i("Property=%s changed", pProperty->key);
            sg_control_msg_arrived = true;
            return;
        }
    }

    Log_e("Property=%s changed no match", pProperty->key);
}

/****************************************************************************
 * Name:  _register_data_template_property
 * Description:
 * @brief       register data template propery
 * @param[in]   pTemplate_client: mqtt data template client
 * @return  0 when success, or err code for failure
 ****************************************************************************/

static int _register_data_template_property(void *pTemplate_client)
{
    int i, rc;

    for (i = 0; i < TOTAL_PROPERTY_COUNT; i++) {
        rc = IOT_Template_Register_Property(pTemplate_client, &sg_DataTemplate[i].data_property, OnControlMsgCallback); /* 注冊单前设备的数据模板属性 */
        if (rc != QCLOUD_RET_SUCCESS) {
            rc = IOT_Template_Destroy(pTemplate_client);
            Log_e("register device data template property failed, err: %d", rc);
            return rc;
        } else {
            Log_i("data template property=%s registered.", sg_DataTemplate[i].data_property.key);
        }
    }

    return QCLOUD_RET_SUCCESS;
}

/****************************************************************************
 * Name:  get_property_state
 * Description:
 * @brief       get property state, changed or not
 * @param[in]   pProperyData: propery state data
 * @return  0: no change, 1: changed
 ****************************************************************************/

static eDataState get_property_state(void *pProperyData)
{
    int i;

    for (i = 0; i < TOTAL_PROPERTY_COUNT; i++) {
        if (sg_DataTemplate[i].data_property.data == pProperyData) {
            return sg_DataTemplate[i].state;
        }
    }

    Log_e("no property matched");
    return eNOCHANGE;
}

/****************************************************************************
 * Name:  deal_down_stream_user_logic
 * Description:
 * @brief       demo for light logic conttrol
 * @param[in]   client: mqtt data template client
 * @param[in]   light: product light propery
 ****************************************************************************/

static void deal_down_stream_user_logic(void *client, ProductDataDefine *light)
{
    int  i;
    char brightness_bar[]   = "||||||||||||||||||||";
    int  brightness_bar_len = strlen(brightness_bar);

    /* using console log to show brightness change */
    brightness_bar_len =
        (light->m_brightness >= 100) ? brightness_bar_len : (int)((light->m_brightness * brightness_bar_len) / 100);
    for (i = brightness_bar_len; i < strlen(brightness_bar); i++) {
        brightness_bar[i] = '-';
    }

    if (light->m_light_switch) {
        HAL_Printf("\n[  light is on  ]|[brightness:%s]|[%s]\n\n", brightness_bar, light->m_name);
    } else {
        HAL_Printf("\n[  light is off ]|[brightness:%s]|[%s]\n\n", brightness_bar, light->m_name);
    }
    HAL_Printf("\n[  light switch is |[%d]\n\n", light->m_light_switch);
    HAL_Printf("\n[  light color is |[%d]\n\n",  light->m_color);
    HAL_Printf("\n[  light brightness is |[%d]\n\n",  light->m_brightness);

    /** hardware control **/
    int ret = ecr_led_diver_ctrl(light);
    if (ret != 0)
    {
        Log_e("\n light hardware control error\n");
    }

    if (eCHANGED == get_property_state(&light->m_light_switch)) {
        if (light->m_light_switch) {
            HAL_Printf("light on\n");
        }
    }
#ifdef EVENT_POST_ENABLED  //开宏即可
    if (eCHANGED == get_property_state(&light->m_light_switch)) {
        if (light->m_light_switch) {
            // memset(sg_message, 0, MAX_EVENT_STR_MESSAGE_LEN);
            // strcpy(sg_message,"light on");
            // sg_status = 1;
            *(TYPE_DEF_TEMPLATE_BOOL *)g_events[0].pEventData[0].data = 1;
            memset((TYPE_DEF_TEMPLATE_STRING *)g_events[0].pEventData[1].data, 0, MAX_EVENT_STR_MESSAGE_LEN);
            strcpy((TYPE_DEF_TEMPLATE_STRING *)g_events[0].pEventData[1].data, "light on");
        } else {
            // memset(sg_message, 0, MAX_EVENT_STR_MESSAGE_LEN);
            // strcpy(sg_message,"light off");
            // sg_status = 0;
            *(TYPE_DEF_TEMPLATE_BOOL *)g_events[0].pEventData[0].data = 0;
            memset((TYPE_DEF_TEMPLATE_STRING *)g_events[0].pEventData[1].data, 0, MAX_EVENT_STR_MESSAGE_LEN);
            strcpy((TYPE_DEF_TEMPLATE_STRING *)g_events[0].pEventData[1].data, "light off");
        }

        /* switch state changed set EVENT0 flag, the events will be posted by eventPostCheck */
        IOT_Event_setFlag(client, FLAG_EVENT0);
    }
#endif
}

/****************************************************************************
 * Name:  cycle_monitor
 * Description:
 * @brief       example for cycle monitor, you can delete this for your needs
 * @param[in]   client: mqtt data template client
 * @param[in]   reportTimer: send report time
 ****************************************************************************/

static void cycle_monitor(void *client, Timer *reportTimer)
{
    // int i;

    if (expired(reportTimer)) {
        // for (i = 0; i < TOTAL_PROPERTY_COUNT; i++) {
        //     DeviceProperty *pReportData = &(sg_DataTemplate[i].data_property);
        //     /* simulate brightness changes */
        //     if (0 == strcmp(pReportData->key, "brightness")) {
        //         int *brightness = (int *)pReportData->data;
        //         *brightness += 5;
        //         if (*brightness > 100)
        //             *brightness = 0;

        //          //set_propery_state(pReportData->data, eCHANGED);
        //     } else {
        //          HAL_Printf("11111111\n");
        //          //set_propery_state(&(sg_DataTemplate[i].data_property.data), eCHANGED);
        //     }

        //     countdown_ms(reportTimer, 10000);
        // }
        if(IOT_Template_IsConnected(client)) //客户端保持连接状态
        {
            Log_i("qcloud client is online");
        }
        countdown_ms(reportTimer, 3000);
    }
}

/****************************************************************************
 * Name:  _refresh_local_property
 * Description:
 * @brief       get local property data, like sensor data
 * @param[in]   client: mqtt data template client
 ****************************************************************************/

static void _refresh_local_property(void *client)
{
    // add your local property refresh logic, cycle monitor for example
    cycle_monitor(client, &sg_MonitorClient);
}

/****************************************************************************
 * Name:  deal_up_stream_user_logic
 * Description:
 * @brief       demo for up-stream code, and count of changed propery
 * @param[in]   client: mqtt data template client
 * @param[out]  pReportDataList: array of report device property
 * @param[out]  pCount: count of changed propery state
 * @return  0 when success, or err code for failure
 ****************************************************************************/

static int deal_up_stream_user_logic(void *client, DeviceProperty *pReportDataList[], int *pCount)
{
    int i, j;

    /* refresh local property */
    _refresh_local_property(client);

    for (i = 0, j = 0; i < TOTAL_PROPERTY_COUNT; i++) {
        if (eCHANGED == sg_DataTemplate[i].state) {
            pReportDataList[j++]     = &(sg_DataTemplate[i].data_property);
            sg_DataTemplate[i].state = eNOCHANGE;
        }
    }
    *pCount = j;

    return (*pCount > 0) ? QCLOUD_RET_SUCCESS : QCLOUD_ERR_FAILURE;
}

/****************************************************************************
 * Name:  _get_sys_info
 * Description:
 * @brief       You should get the real info for your device, here just for example
 *              init system information, and construct up stream template
 * @param[in]   handle: mqtt data template client
 * @param[in]   pJsonDoc: json data that has been used
 * @param[in]   sizeOfBuffer: size of total send buffer
 * @return  0 when success, or err code for failure
 ****************************************************************************/

static int _get_sys_info(void *handle, char *pJsonDoc, size_t sizeOfBuffer)
{
    /*platform info has at least one of module_hardinfo/module_softinfo/fw_ver property*/
    DeviceProperty platform_info[] = {
        {.key = "module_hardinfo", .type = TYPE_TEMPLATE_STRING, .data = "ESWIN"},
        {.key = "module_softinfo", .type = TYPE_TEMPLATE_STRING, .data = "V1.0"},
        {.key = "fw_ver", .type = TYPE_TEMPLATE_STRING, .data = QCLOUD_IOT_DEVICE_SDK_VERSION},
        {.key = "imei", .type = TYPE_TEMPLATE_STRING, .data = "11-22-33-44"},
        {.key = "lat", .type = TYPE_TEMPLATE_STRING, .data = "22.546015"},
        {.key = "lon", .type = TYPE_TEMPLATE_STRING, .data = "113.941125"},
        {.key = NULL, .data = NULL}  // end
    };

    /*self define info*/
    DeviceProperty self_info[] = {
        {.key = "append_info", .type = TYPE_TEMPLATE_STRING, .data = "ESWIN6600 test board demo"},
        {.key = NULL, .data = NULL}  // end
    };
    /* construct the system information to be reported */
    return IOT_Template_JSON_ConstructSysInfo(handle, pJsonDoc, sizeOfBuffer, platform_info, self_info);
}

/****************************************************************************
 * Name:  ecr_get_led_info
 * Description:
 * @brief       get led information from NV
 * @param[in]   sg_ProductData: product propery data
 ****************************************************************************/

void ecr_get_led_info(ProductDataDefine *sg_ProductData)
{
    int brightness_len, color_len, switch_len;
    int brightness_my = 0, color_my = 0;
    int switch_my = 0;
    switch_len = customer_get_env_blob("DevSwitch", (int *)&switch_my,  sizeof(switch_my), NULL);
    color_len = customer_get_env_blob("DevColor", (int *)&color_my,  sizeof(color_my), NULL);
    brightness_len = customer_get_env_blob("DevBrightness", (int *)&brightness_my,  sizeof(brightness_my), NULL);

    if ((brightness_len != 0) && (color_len != 0) && (switch_len != '0')) {
        Log_i("fread succeed!, m_switch = %d, m_color = %d, m_brightness = %d\n\r", switch_my, color_my, brightness_my);
        sg_ProductData->m_light_switch = switch_my;
        sg_ProductData->m_color = color_my;
        sg_ProductData->m_brightness = brightness_my;
    } else {
        Log_e("fread failed! not read led data\n");
    }
}

/****************************************************************************
 * Name:  ecr_qcloud_led_ctrl
 * Description:
 * @brief       led control main function
 * @param[in]   client: mqtt data template client
 * @return  0 when success, or err code for failure
 ****************************************************************************/

int ecr_qcloud_led_ctrl(Qcloud_IoT_Template *client)
{
    DeviceProperty *pReportDataList[TOTAL_PROPERTY_COUNT];
    sReplyPara      replyPara;
    int             ReportCount;
    int             rc;
    int             led_failed_flag = 0;
    int             disconnect_cnt = 0;
    /* init data template */
    _init_data_template();/* template propery define */

    /* register data template propertys here */
    rc = _register_data_template_property(client);/* regeister template propery, and set callback function */
    if (rc == QCLOUD_RET_SUCCESS) {
        Log_i("Register data template propertys Success\n");
    } else {
        Log_e("Register data template propertys Failed: %d\n", rc);
        led_failed_flag = 1;
        goto exit;
    }

    /* register data template actions here */
#ifdef ACTION_ENABLED
    rc = _register_data_template_action(client);/* regeister template propery, and set callback function */
    if (rc == QCLOUD_RET_SUCCESS) {
        Log_i("Register data template actions Success\n");
    } else {
        Log_e("Register data template actions Failed: %d\n", rc);
        led_failed_flag = 1;
        goto exit;
    }
#endif

    /* report device info, then you can manager your product by these info, like position */
    rc = _get_sys_info(client, sg_data_report_buffer, sg_data_report_buffersize); //上报设备信息
    if (QCLOUD_RET_SUCCESS == rc) {
        rc = IOT_Template_Report_SysInfo_Sync(client, sg_data_report_buffer, sg_data_report_buffersize,
                                              MQTT_TIMEOUT_VALUE_MS); /* 同步方式上报系统信息 */
        if (rc != QCLOUD_RET_SUCCESS) {
            Log_e("Report system info fail, err: %d\n", rc);
            led_failed_flag = 1;
            goto exit;
        }
    } else {
        Log_e("Get system info fail, err: %d\n", rc);
    }

    /* sync the property value during offline */
    rc = IOT_Template_GetStatus_sync(client, MQTT_TIMEOUT_VALUE_MS);  /* 同步方式获取数据模板属性数据  离线 */
    if (rc != QCLOUD_RET_SUCCESS) {
        Log_e("Get data status fail, err: %d\n", rc);
        led_failed_flag = 1;
        goto exit;
    } else {
        Log_d("Get data status success\n");
    }

    /*读NV，灯设备上电复位属性初始化*/
    ecr_get_led_info(&sg_ProductData);

    /* update local property status */
    deal_down_stream_user_logic(client, &sg_ProductData); /* 下发控制，设备设置初始状态 */

    /* init a timer for cycle report, you could delete it or not for your needs */
    InitTimer(&sg_MonitorClient);
    countdown_ms(&sg_MonitorClient, 10000);

    /* 使用whlie循环，线程占用 */

led_ctrl_start:
    while (true) {
        if (!IOT_Template_IsConnected(client)) {
            disconnect_cnt++;
            if (disconnect_cnt >= 20) {
                led_failed_flag = 2;
                Log_e("disconnected over %d seconds. Quit!\n", disconnect_cnt);
                break;
            }
            HAL_SleepMs(1000);
        }
        else
        {
            disconnect_cnt = 0;
        }

        rc = IOT_Template_Yield(client, 200);
        if (rc == QCLOUD_ERR_MQTT_ATTEMPTING_RECONNECT) {
            HAL_SleepMs(1000);
            continue;
        } else if (rc != QCLOUD_RET_SUCCESS) {
            Log_e("Exit loop caused of errCode: %d", rc);
        }
        
        /* handle control msg from server */
        if (sg_control_msg_arrived) { /* 服务器下发控制消息，回调函数标志量设为true */
            deal_down_stream_user_logic(client, &sg_ProductData);    /* 控制下发 */
            /* control msg should reply, otherwise server treat device didn't receive and retain the msg which would be
             * get by  get status*/
            memset((char *)&replyPara, 0, sizeof(sReplyPara));
            replyPara.code          = eDEAL_SUCCESS;
            replyPara.timeout_ms    = QCLOUD_IOT_MQTT_COMMAND_TIMEOUT;
            replyPara.status_msg[0] = '\0';  /* add extra info to replyPara.status_msg when error occured */

            rc = IOT_Template_ControlReply(client, sg_data_report_buffer, sg_data_report_buffersize, &replyPara); /* 回复收到的数据模板控制消息 */
            if (rc == QCLOUD_RET_SUCCESS) {
                Log_d("Contol msg reply success\n");
                sg_control_msg_arrived = false;
            } else {
                Log_e("Contol msg reply failed, err: %d\n", rc);
            }
        /*存NV,灯设备属性*/
        Log_i("write NV, m_switch = %d, m_color = %d, m_brightness = %d\n\r", sg_ProductData.m_light_switch, sg_ProductData.m_color, sg_ProductData.m_brightness);
        customer_set_env_blob("DevSwitch", &sg_ProductData.m_light_switch, sizeof(&sg_ProductData.m_light_switch));
        customer_set_env_blob("DevColor", &sg_ProductData.m_color, sizeof(&sg_ProductData.m_color));
        customer_set_env_blob("DevBrightness", &sg_ProductData.m_brightness, sizeof(&sg_ProductData.m_brightness));
        }

        /*report msg to server*/
        /*report the lastest properties's status*/
        if (QCLOUD_RET_SUCCESS == deal_up_stream_user_logic(client, pReportDataList, &ReportCount)) {
            rc = IOT_Template_JSON_ConstructReportArray(client, sg_data_report_buffer, sg_data_report_buffersize,
                                                        ReportCount, pReportDataList); /* 构造待上报的系统信息 */
            if (rc == QCLOUD_RET_SUCCESS) {
                rc = IOT_Template_Report(client, sg_data_report_buffer, sg_data_report_buffersize,
                                         OnReportReplyCallback, NULL, QCLOUD_IOT_MQTT_COMMAND_TIMEOUT); /* 异步方式上报数据模板属性 */
                if (rc == QCLOUD_RET_SUCCESS) {
                    Log_i("data template report success\n");
                } else {
                    Log_e("data template report failed, err: %d\n", rc);
                }
            } else {
                Log_e("construct report data failed, err: %d\n", rc);
            }
        }

#ifdef EVENT_POST_ENABLED
        eventPostCheck(client);
#endif
        HAL_SleepMs(1000);
    }

exit:
    while(true)
    {
        if(!IOT_Template_IsConnected(client))
        {
            Log_e("-------- led wait connect------\n");
            HAL_SleepMs(1000);
        }
        else
        {
            if(led_failed_flag == 2)
            {
                Log_i("-------- led wifi  connect------\n");
                disconnect_cnt = 0;
                led_failed_flag = 0;
                goto led_ctrl_start;
            }
#ifdef MULTITHREAD_ENABLED
            IOT_Template_Stop_Yield_Thread(client);
#endif
            rc = IOT_Template_Destroy(client);
            break;
        }
    }
    return rc;
}
